// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDruGC26MBlG3vH7hXTlVWxsmK6YR1GF-s',
    appId: '1:384378965765:web:14af4913d0b6757a11b16c',
    messagingSenderId: '384378965765',
    projectId: 'deep-link-app-bc3e6',
    authDomain: 'deep-link-app-bc3e6.firebaseapp.com',
    storageBucket: 'deep-link-app-bc3e6.appspot.com',
    measurementId: 'G-NK764MQKWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoODopg9-CISFp9I7ZFzU9QjQ_6jlmNhE',
    appId: '1:384378965765:android:c3a7cb222062f95c11b16c',
    messagingSenderId: '384378965765',
    projectId: 'deep-link-app-bc3e6',
    storageBucket: 'deep-link-app-bc3e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG9yDST36KWU08ojVUpE6x50uuHPyFygA',
    appId: '1:384378965765:ios:42e657611e1887f411b16c',
    messagingSenderId: '384378965765',
    projectId: 'deep-link-app-bc3e6',
    storageBucket: 'deep-link-app-bc3e6.appspot.com',
    iosClientId: '384378965765-kf78ethjdkdk43f0dhre7g14saacqnlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepLinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG9yDST36KWU08ojVUpE6x50uuHPyFygA',
    appId: '1:384378965765:ios:42e657611e1887f411b16c',
    messagingSenderId: '384378965765',
    projectId: 'deep-link-app-bc3e6',
    storageBucket: 'deep-link-app-bc3e6.appspot.com',
    iosClientId: '384378965765-kf78ethjdkdk43f0dhre7g14saacqnlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepLinkApp',
  );
}
